os: osx
osx_image: xcode10.1
language: swift

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - swift test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT